resources:
  limits:
    cpus: 2.0
    memory: 4096

synapse:
  postgres_image_selector: postgres_18_image
  db_user: synapse
  db_password: synapse
  server_name: example.com
  report_stats: no
  allow_registration: false
  allow_registration_without_verification: false

network:
  web_port:
    bind_mode: published
    port_number: 8008
  certificate_id: null

run_as:
  user: 568
  group: 568

ix_volumes:
  synapse_data: /opt/tests/mnt/synapse/data
  postgres_data: /opt/tests/mnt/synapse/postgres_data

storage:
  uploads:
    type: ix_volume
    ix_volume_config:
      dataset_name: uploads
      create_host_path: true
  public:
    type: ix_volume
    ix_volume_config:
      dataset_name: public
      create_host_path: true
  themes:
    type: ix_volume
    ix_volume_config:
      dataset_name: themes
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  additional_storage: []
