{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.synapse_container_name, "image") %}
{% set perm_container = tpl.deps.perms(values.consts.perms_container_name) %}
{% set perms_config = {"uid": values.run_as.user, "gid": values.run_as.group, "mode": "check"} %}

{% set pg_config = {
  "user": values.consts.db_user,
  "password": values.synapse.db_password,
  "database": values.consts.db_name,
  "volume": values.storage.postgres_data,
} %}
{% set postgres = tpl.deps.postgres(
  values.consts.postgres_container_name,
  values.synapse.postgres_image_selector,
  pg_config, perm_container
) %}

{% set proto = "https" if values.network.certificate_id else "http" %}
{% do c1.set_user(values.run_as.user, values.run_as.group) %}
{% do c1.depends.add_dependency(values.consts.postgres_container_name, "service_healthy") %}
{% do c1.healthcheck.set_test("wget", {"port": values.network.web_port.port_number, "path": "/health", "scheme": proto}) %}

{% do c1.environment.add_env("SYNAPSE_REPORT_STATS", values.synapse.report_stats) %}
{% do c1.environment.add_env("SYNAPSE_HTTP_PORT", values.network.web_port.port_number) %}
{% do c1.environment.add_env("DATABASE_URL", postgres.get_url("postgres")) %}
{% do c1.environment.add_env("SYNAPSE_SERVER_NAME", values.synapse.server_name) %}

{% do c1.environment.add_user_envs(values.synapse.additional_envs) %}

{% do c1.add_port(values.network.web_port) %}

{% do c1.add_storage(values.consts.synapse_data, values.storage.synapse_data) %}
{% do perm_container.add_or_skip_action("synapse_data", values.storage.synapse_data, perms_config) %}

{% if perm_container.has_actions() %}
  {% do perm_container.activate() %}
  {% do c1.depends.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
  {% do postgres.add_dependency(values.consts.perms_container_name, "service_completed_successfully") %}
{% endif %}

{% do tpl.portals.add(values.network.web_port, {"scheme": proto}) %}

{{ tpl.render() | tojson }}
